name: Build Scan Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"

  workflow_dispatch:
    inputs:
      publish:
        description: "Publish approved images to Amazon ECR"
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "671662643382"

jobs:
  build-scan-push:
    name: Build and scan ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            context: ./backend
            repository: minishop-backend

          - name: frontend
            context: ./frontend
            repository: minishop-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set local image name
        run: |
          echo "IMAGE=${{ matrix.repository }}:${GITHUB_SHA}" >> "$GITHUB_ENV"

      - name: Build image
        run: |
          docker build \
            --tag "$IMAGE" \
            "${{ matrix.context }}"

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Configure AWS credentials
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish == true }}
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish == true }}
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR image name
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish == true }}
        run: |
          echo "ECR_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ matrix.repository }}:${GITHUB_SHA}" >> "$GITHUB_ENV"

      - name: Tag image for Amazon ECR
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish == true }}
        run: |
          docker tag "$IMAGE" "$ECR_IMAGE"

      - name: Push image to Amazon ECR
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish == true }}
        run: |
          docker push "$ECR_IMAGE"
